- hosts: localhost
  connection: local
  tasks:
    - name: Creating resource group - "{{ name }}"
      azure_rm_resourcegroup:
        name: "{{ name }}"
        location: "{{ location }}"
        tags:
          DevOwner: naveentestuser@gmail.com
      register: rg
    - debug:
        var: rg